/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Place } from "./Place";
import { PlaceCountArgs } from "./PlaceCountArgs";
import { PlaceFindManyArgs } from "./PlaceFindManyArgs";
import { PlaceFindUniqueArgs } from "./PlaceFindUniqueArgs";
import { CreatePlaceArgs } from "./CreatePlaceArgs";
import { UpdatePlaceArgs } from "./UpdatePlaceArgs";
import { DeletePlaceArgs } from "./DeletePlaceArgs";
import { RecommendationFindManyArgs } from "../../recommendation/base/RecommendationFindManyArgs";
import { Recommendation } from "../../recommendation/base/Recommendation";
import { Subcategory } from "../../subcategory/base/Subcategory";
import { SubSubcategory } from "../../subSubcategory/base/SubSubcategory";
import { Category } from "../../category/base/Category";
import { PlaceService } from "../place.service";
@graphql.Resolver(() => Place)
export class PlaceResolverBase {
  constructor(protected readonly service: PlaceService) {}

  async _placesMeta(
    @graphql.Args() args: PlaceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Place])
  async places(@graphql.Args() args: PlaceFindManyArgs): Promise<Place[]> {
    return this.service.places(args);
  }

  @graphql.Query(() => Place, { nullable: true })
  async place(
    @graphql.Args() args: PlaceFindUniqueArgs
  ): Promise<Place | null> {
    const result = await this.service.place(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Place)
  async createPlace(@graphql.Args() args: CreatePlaceArgs): Promise<Place> {
    return await this.service.createPlace({
      ...args,
      data: {
        ...args.data,

        subcategory: args.data.subcategory
          ? {
              connect: args.data.subcategory,
            }
          : undefined,

        subSubcategory: args.data.subSubcategory
          ? {
              connect: args.data.subSubcategory,
            }
          : undefined,

        category: args.data.category
          ? {
              connect: args.data.category,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Place)
  async updatePlace(
    @graphql.Args() args: UpdatePlaceArgs
  ): Promise<Place | null> {
    try {
      return await this.service.updatePlace({
        ...args,
        data: {
          ...args.data,

          subcategory: args.data.subcategory
            ? {
                connect: args.data.subcategory,
              }
            : undefined,

          subSubcategory: args.data.subSubcategory
            ? {
                connect: args.data.subSubcategory,
              }
            : undefined,

          category: args.data.category
            ? {
                connect: args.data.category,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Place)
  async deletePlace(
    @graphql.Args() args: DeletePlaceArgs
  ): Promise<Place | null> {
    try {
      return await this.service.deletePlace(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Recommendation], { name: "recommendations" })
  async findRecommendations(
    @graphql.Parent() parent: Place,
    @graphql.Args() args: RecommendationFindManyArgs
  ): Promise<Recommendation[]> {
    const results = await this.service.findRecommendations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Subcategory, {
    nullable: true,
    name: "subcategory",
  })
  async getSubcategory(
    @graphql.Parent() parent: Place
  ): Promise<Subcategory | null> {
    const result = await this.service.getSubcategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => SubSubcategory, {
    nullable: true,
    name: "subSubcategory",
  })
  async getSubSubcategory(
    @graphql.Parent() parent: Place
  ): Promise<SubSubcategory | null> {
    const result = await this.service.getSubSubcategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Category, {
    nullable: true,
    name: "category",
  })
  async getCategory(@graphql.Parent() parent: Place): Promise<Category | null> {
    const result = await this.service.getCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
