/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { GuideService } from "../guide.service";
import { GuideCreateInput } from "./GuideCreateInput";
import { Guide } from "./Guide";
import { GuideFindManyArgs } from "./GuideFindManyArgs";
import { GuideWhereUniqueInput } from "./GuideWhereUniqueInput";
import { GuideUpdateInput } from "./GuideUpdateInput";
import { ExperienceFindManyArgs } from "../../experience/base/ExperienceFindManyArgs";
import { Experience } from "../../experience/base/Experience";
import { ExperienceWhereUniqueInput } from "../../experience/base/ExperienceWhereUniqueInput";

export class GuideControllerBase {
  constructor(protected readonly service: GuideService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Guide })
  async createGuide(@common.Body() data: GuideCreateInput): Promise<Guide> {
    return await this.service.createGuide({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rating: true,
        availability: true,
        coverage: true,
        name: true,
        bio: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Guide] })
  @ApiNestedQuery(GuideFindManyArgs)
  async guides(@common.Req() request: Request): Promise<Guide[]> {
    const args = plainToClass(GuideFindManyArgs, request.query);
    return this.service.guides({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rating: true,
        availability: true,
        coverage: true,
        name: true,
        bio: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Guide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async guide(
    @common.Param() params: GuideWhereUniqueInput
  ): Promise<Guide | null> {
    const result = await this.service.guide({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        rating: true,
        availability: true,
        coverage: true,
        name: true,
        bio: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Guide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateGuide(
    @common.Param() params: GuideWhereUniqueInput,
    @common.Body() data: GuideUpdateInput
  ): Promise<Guide | null> {
    try {
      return await this.service.updateGuide({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          rating: true,
          availability: true,
          coverage: true,
          name: true,
          bio: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Guide })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteGuide(
    @common.Param() params: GuideWhereUniqueInput
  ): Promise<Guide | null> {
    try {
      return await this.service.deleteGuide({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          rating: true,
          availability: true,
          coverage: true,
          name: true,
          bio: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/experiences")
  @ApiNestedQuery(ExperienceFindManyArgs)
  async findExperiences(
    @common.Req() request: Request,
    @common.Param() params: GuideWhereUniqueInput
  ): Promise<Experience[]> {
    const query = plainToClass(ExperienceFindManyArgs, request.query);
    const results = await this.service.findExperiences(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        duration: true,
        price: true,
        pricingRule: true,
        description: true,

        guide: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/experiences")
  async connectExperiences(
    @common.Param() params: GuideWhereUniqueInput,
    @common.Body() body: ExperienceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      experiences: {
        connect: body,
      },
    };
    await this.service.updateGuide({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/experiences")
  async updateExperiences(
    @common.Param() params: GuideWhereUniqueInput,
    @common.Body() body: ExperienceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      experiences: {
        set: body,
      },
    };
    await this.service.updateGuide({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/experiences")
  async disconnectExperiences(
    @common.Param() params: GuideWhereUniqueInput,
    @common.Body() body: ExperienceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      experiences: {
        disconnect: body,
      },
    };
    await this.service.updateGuide({
      where: params,
      data,
      select: { id: true },
    });
  }
}
