/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Experience } from "./Experience";
import { ExperienceCountArgs } from "./ExperienceCountArgs";
import { ExperienceFindManyArgs } from "./ExperienceFindManyArgs";
import { ExperienceFindUniqueArgs } from "./ExperienceFindUniqueArgs";
import { CreateExperienceArgs } from "./CreateExperienceArgs";
import { UpdateExperienceArgs } from "./UpdateExperienceArgs";
import { DeleteExperienceArgs } from "./DeleteExperienceArgs";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { Guide } from "../../guide/base/Guide";
import { ExperienceService } from "../experience.service";
@graphql.Resolver(() => Experience)
export class ExperienceResolverBase {
  constructor(protected readonly service: ExperienceService) {}

  async _experiencesMeta(
    @graphql.Args() args: ExperienceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Experience])
  async experiences(
    @graphql.Args() args: ExperienceFindManyArgs
  ): Promise<Experience[]> {
    return this.service.experiences(args);
  }

  @graphql.Query(() => Experience, { nullable: true })
  async experience(
    @graphql.Args() args: ExperienceFindUniqueArgs
  ): Promise<Experience | null> {
    const result = await this.service.experience(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Experience)
  async createExperience(
    @graphql.Args() args: CreateExperienceArgs
  ): Promise<Experience> {
    return await this.service.createExperience({
      ...args,
      data: {
        ...args.data,

        guide: args.data.guide
          ? {
              connect: args.data.guide,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Experience)
  async updateExperience(
    @graphql.Args() args: UpdateExperienceArgs
  ): Promise<Experience | null> {
    try {
      return await this.service.updateExperience({
        ...args,
        data: {
          ...args.data,

          guide: args.data.guide
            ? {
                connect: args.data.guide,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Experience)
  async deleteExperience(
    @graphql.Args() args: DeleteExperienceArgs
  ): Promise<Experience | null> {
    try {
      return await this.service.deleteExperience(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  async findBookings(
    @graphql.Parent() parent: Experience,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Guide, {
    nullable: true,
    name: "guide",
  })
  async getGuide(@graphql.Parent() parent: Experience): Promise<Guide | null> {
    const result = await this.service.getGuide(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
