/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SubSubcategory } from "./SubSubcategory";
import { SubSubcategoryCountArgs } from "./SubSubcategoryCountArgs";
import { SubSubcategoryFindManyArgs } from "./SubSubcategoryFindManyArgs";
import { SubSubcategoryFindUniqueArgs } from "./SubSubcategoryFindUniqueArgs";
import { CreateSubSubcategoryArgs } from "./CreateSubSubcategoryArgs";
import { UpdateSubSubcategoryArgs } from "./UpdateSubSubcategoryArgs";
import { DeleteSubSubcategoryArgs } from "./DeleteSubSubcategoryArgs";
import { PlaceFindManyArgs } from "../../place/base/PlaceFindManyArgs";
import { Place } from "../../place/base/Place";
import { Subcategory } from "../../subcategory/base/Subcategory";
import { SubSubcategoryService } from "../subSubcategory.service";
@graphql.Resolver(() => SubSubcategory)
export class SubSubcategoryResolverBase {
  constructor(protected readonly service: SubSubcategoryService) {}

  async _subSubcategoriesMeta(
    @graphql.Args() args: SubSubcategoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SubSubcategory])
  async subSubcategories(
    @graphql.Args() args: SubSubcategoryFindManyArgs
  ): Promise<SubSubcategory[]> {
    return this.service.subSubcategories(args);
  }

  @graphql.Query(() => SubSubcategory, { nullable: true })
  async subSubcategory(
    @graphql.Args() args: SubSubcategoryFindUniqueArgs
  ): Promise<SubSubcategory | null> {
    const result = await this.service.subSubcategory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SubSubcategory)
  async createSubSubcategory(
    @graphql.Args() args: CreateSubSubcategoryArgs
  ): Promise<SubSubcategory> {
    return await this.service.createSubSubcategory({
      ...args,
      data: {
        ...args.data,

        subcategory: args.data.subcategory
          ? {
              connect: args.data.subcategory,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => SubSubcategory)
  async updateSubSubcategory(
    @graphql.Args() args: UpdateSubSubcategoryArgs
  ): Promise<SubSubcategory | null> {
    try {
      return await this.service.updateSubSubcategory({
        ...args,
        data: {
          ...args.data,

          subcategory: args.data.subcategory
            ? {
                connect: args.data.subcategory,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SubSubcategory)
  async deleteSubSubcategory(
    @graphql.Args() args: DeleteSubSubcategoryArgs
  ): Promise<SubSubcategory | null> {
    try {
      return await this.service.deleteSubSubcategory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Place], { name: "places" })
  async findPlaces(
    @graphql.Parent() parent: SubSubcategory,
    @graphql.Args() args: PlaceFindManyArgs
  ): Promise<Place[]> {
    const results = await this.service.findPlaces(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Subcategory, {
    nullable: true,
    name: "subcategory",
  })
  async getSubcategory(
    @graphql.Parent() parent: SubSubcategory
  ): Promise<Subcategory | null> {
    const result = await this.service.getSubcategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
